environment:

  matrix:

    - PYTHON: "27"

    - PYTHON: "34"

    - PYTHON: "35"
    
    - PYTHON: "36"
    
image: Visual Studio 2015
platform:
  - x64

install:
  - nuget install libxml2 libxslt
  - cmd: python -m pip install lxml

build: off
