environment:

  matrix:

    - PYTHON: "27"

    - PYTHON: "34"

    - PYTHON: "35"
    
    - PYTHON: "36"
    
image: Visual Studio 2015
platform:
  - x64

install:
  - cmd: git clone https://github.com/mhils/libxml2-win-binaries
  - cmd: cd libxml2-win-binaries
  - cmd: git submodule update --init --recursive
  - ps: install-module pscx -scope CurrentUser
  - ps: Find-Package pscx | ? ProviderName -eq PSModule | Install-Package -Force
  - ps: .\build.ps1 -x64:$true -vs2008:$false
  
  - "C:\\Python%PYTHON%-x64\\python.exe -m pip install lxml"

build: off
